commit:
  dependents:
    - repo: metabahn/commit-test
    - repo: metabahn/llhttp

  groups:
    - name: "ruby"
      templates:
        - source: "ruby/rspec.erb"
          destination: "./.rspec"

      templates:
        - source: "ruby/ruby-version.erb"
          destination: "./.ruby-version"

      templates:
        - source: "ruby/standard.yml.erb"
          destination: "./.standard.yml"

    - name: "ruby-gem"
      templates:
        - source: "ruby/gem/gem.gemspec.erb"
          destination: "./{config.project.slug}.gemspec"

    - name: "oss"
      templates:
        - source: "licenses/{config.license.slug}.erb"
          destination: "./LICENSE"
