commit:
  dependents:
    - repo: metabahn/commit-test
    - repo: metabahn/contentfs
    - repo: metabahn/corerb
    - repo: metabahn/isrb
    - repo: metabahn/llhttp
    - repo: metabahn/stringdoc

  groups:
    - name: "base"
      templates:
        - source: "editor/doteditorconfig.erb"
          destination: "./.editorconfig"

    - name: "git"
      templates:
        - source: "git/dotgitignore.erb"
          destination: "./.gitignore"

    - name: "oss"
      templates:
        - source: "licenses/{config.license.slug}.erb"
          destination: "./LICENSE"

    - name: "ruby"
      templates:
        - source: "ruby/dotruby-version.erb"
          destination: "./.ruby-version"

    - name: "ruby-rspec"
      templates:
        - source: "ruby/rspec/dotrspec.erb"
          destination: "./.rspec"
        - source: "ruby/rspec/initialize.rb.erb"
          destination: "./spec/initialize.rb"
        - source: "ruby/rspec/initializers/configure.rb.erb"
          destination: "./spec/initializers/configure.rb"
        - source: "ruby/rspec/initializers/matchers.rb.erb"
          destination: "./spec/initializers/matchers.rb"

    - name: "ruby-standard"
      templates:
        - source: "ruby/dotstandard.yml.erb"
          destination: "./.standard.yml"

    - name: "ruby-gem"
      config:
        git:
          ignore:
            - "*.bundle"
            - "*.gem"
            - "Gemfile.lock"
            - ".ruby-version"

      templates:
        - source: "ruby/gem/gem.gemspec.erb"
          destination: "./{config.project.slug}.gemspec"
