commit:
  dependents:
    - repo: metabahn/commit-test
    - repo: metabahn/fscontent
    - repo: metabahn/llhttp

  groups:
    - name: "git"
      templates:
        - source: "git/gitignore.erb"
          destination: "./.gitignore"

    - name: "oss"
      templates:
        - source: "licenses/{config.license.slug}.erb"
          destination: "./LICENSE"

    - name: "ruby"
      templates:
        - source: "ruby/ruby-version.erb"
          destination: "./.ruby-version"

    - name: "ruby-rspec"
      templates:
        - source: "ruby/rspec.erb"
          destination: "./.rspec"

    - name: "ruby-standard"
      templates:
        - source: "ruby/standard.yml.erb"
          destination: "./.standard.yml"

    - name: "ruby-gem"
      config:
        git:
          ignore:
            - "*.bundle"
            - "Gemfile.lock"
            - ".ruby-version"

      templates:
        - source: "ruby/gem/gem.gemspec.erb"
          destination: "./{config.project.slug}.gemspec"
