on:
  push:
  repository_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Checkout commit tools
      uses: actions/checkout@v2
      with:
        repository: metabahn/commit
        path: .commit/tools

    - name: Setup ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Update dependents
      run: ./.commit/tools/bin/update-dependents
      env:
        COMMIT__GIT_EMAIL: "bot@metabahn.com"
        COMMIT__GIT_NAME: "Metabahn Bot"
        COMMIT__GIT_TOKEN: ${{secrets.COMMIT_TOKEN}}
        COMMIT__GIT_USER: "metabahn-bot"
